security:
    encoders:
        Symfony\Component\Security\Core\User\User: sha512
        Mascotas\MascotasBundle\Entity\Usuario: sha512
        encode_as_base64: false
        
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login: ~
        
            logout:
                path: /logout
                target: /mascotas
                
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/mascotas/publicacion/new, roles: ROLE_USER }
        - { path: ^/mascotas/mascota/new, roles: ROLE_USER}
        - { path: ^/mascotas/usuario/new, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/edit, roles: ROLE_ADMIN}
        - { path: ^/update, roles: ROLE_ADMIN}
    providers:
      en_memoria:
        memory:
          users:
            admin: { password: admin, roles: ROLE_ADMIN }
      de_la_base:
        entity:
          { class: Mascotas\MascotasBundle\Entity\Usuario, property: usuario }