security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login: ~

    access_control:
        - { path: ^/mascotas/publicacion/new, roles: ROLE_USER }
        - { path: ^/mascotas/mascota/new, roles: ROLE_ADMIN }
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        in_memory:
            memory:
                users:
                    ryan:  { password: ryanpass, roles: 'ROLE_USER' }
                    admin: { password: yoadministro, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext