security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Mascotas\MascotasBundle\Entity\Usuario: plaintext        
    acl:
          connection: default
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login: 
              default_target_path: /mascotas
        
            logout:
                path: /logout
                target: /mascotas
                invalidate_session: false
                
    role_hierarchy:
        ROLE_ADMIN: ROLE_ADMIN, ROLE_USER, ROLE_MODERATOR 

    access_control:
        - { path: ^/mascotas/publicacion/new, roles: ROLE_USER}
        - { path: ^/mascotas/comentario/new, roles: ROLE_USER}
        - { path: ^/mascotas/panel/admin, roles: ROLE_ADMIN}
        
    providers:
      encadenado:
        chain:
          providers: [enmemoria, de_la_base]
      enmemoria:
        memory:
          users:
            admin: {password: admin, roles: 'ROLE_ADMIN'}
            
            
      de_la_base:
        entity:
          { class: Mascotas\MascotasBundle\Entity\Usuario, property: usuario }