security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Mascotas\MascotasBundle\Entity\Usuario: plaintext
        
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login: ~
        
            logout:
                path: /logout
                target: /mascotas
                
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    access_control:
        - { path: ^/mascotas/publicacion/new, roles: ROLE_USER }
        - { path: ^/mascotas/mascota/new, roles: ROLE_USER}
        
    providers:
      chain_provider:
            entity:
                { class: Mascotas\MascotasBundle\Entity\Usuario, property: usuario }
              