<?php

namespace Mascotas\MascotasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComentarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentarioRepository extends EntityRepository
{
    public function getComentarios($publicacion_id) {
         $qb = $this->createQueryBuilder('c')
                   ->select('c')
                   ->where('c.publicacion = :publicacion_id')
                   ->setParameter('publicacion_id', $publicacion_id);

        return $qb->getQuery()
                  ->getResult();
    }
}
