<?php

namespace Mascotas\MascotasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComentarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentarioRepository extends EntityRepository {

    public function getComentarios($publicacion_id, $nro_pagina) {
        $limit = 10;
        $offset = ( $nro_pagina * $limit ) - $limit;
        $criteria = array('publicacion' => $publicacion_id);
        $orderBy = array('id' => 'desc');

        return $this->findBy($criteria, $orderBy, $limit, $offset);
    }

    public function getCantidad($publicacion_id) {
        $criteria = array('publicacion' => $publicacion_id);
        return ceil(count($this->findBy($criteria)) / 10);
    }

}
