<?php

namespace Mascotas\MascotasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PublicacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicacionRepository extends EntityRepository {

    public function getPagina($nro_pagina) {
        $limit = 5;
        $offset = ($nro_pagina * $limit) - $limit;
        $criteria = array();
        $orderBy = array('id' => 'desc');
        return $this->findBy($criteria, $orderBy, $limit, $offset);
    }

    public function getCantidad() {
        return ceil(count($this->findAll()) / 5);
    }

}

